version: '3'

services:
#  web:
#    build:
#      context: query-api
#      dockerfile: Dockerfile
#    ports:
#      - "8001:8001"
#    depends_on:
#      - "database"
#    networks:
#      - "mynet"

  database:
    image: "mysql:latest"
    container_name: "db-mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "structured_data"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "./resources/db.sql:/docker-entrypoint-initdb.d/db.sql"