server:
  port: 8080

spring:
  main:
    web-application-type: reactive

  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: query-api
          uri: http://localhost:8001
          predicates:
            - Path=/query/**

